<h1 style="text-align: center;">Numerical Python</h1>


Axis 0: Operates column-wise (down the rows). Think of it as "moving vertically."

Axis 1: Operates row-wise (across the columns). Think of it as "moving horizontally."

In [2]:
import numpy as np

### List to numpy array

In [16]:
l=[1,2,3,4]
nl1=np.array(l)
print(nl1,type(nl1))
print(nl1.ndim) # dimension=1

nl2=np.array(l,ndmin=2) # creates 2D array
print(nl2) 

nl5=np.array(l,ndmin=5)
print(nl5) # creates 5D array


#multidimensional array
l1=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(l1)
print(a)
print(a.ndim) # 2

[1 2 3 4] <class 'numpy.ndarray'>
1
[[1 2 3 4]]
[[[[[1 2 3 4]]]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


### Arange fun

In [45]:
a=np.arange(1,10) # 1 to 9 array ( default step 1 )
a1= np.arange(1,6,2) # step 2
a1

array([1, 3, 5])

In [8]:
l=[[1,2,3,3],[4,5,6,6],[7,8,9,9]]
a=np.array(l)
a

print(a.ndim) # 2
print(a.size) # number of elements =9
print(np.size(a,0)) # axis=0 , no of rows =3
print(np.size(a,1)) # axis 1, no of cols = 4


# tuple  (rows,cols)
print(a.shape)
print(np.shape(a))


#Dtype
print(a.dtype) # int32


2
12
3
4
(3, 4)
(3, 4)
int32


### Zeros fun

In [18]:
z=np.zeros(shape=(2,1)) # 2 rows , 1 col
z=np.zeros(shape=(4,3),dtype=int) # 4 rows , 3 cols
z # gives float zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Ones fun

In [17]:
o=np.ones(shape=(2,3)) # 2 rows, 3 cols , float 1s
o= np.ones(shape=(4,3),dtype=int) # int 1s
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Eye fun

In [20]:
# identity matrix
I = np.eye(3)
I=np.eye(4,dtype=int)
I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Empty fun

In [58]:
arr = np.empty((3, 3))
print(arr)

#The np.empty() function allocates memory for the array but does not set its values,
# so the array contains whatever values were already in that part of memory (random, uninitialized data).

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Random fun


In [5]:
# 1. rand - Generates random numbers uniformly distributed in [0,1).
np.random.rand(4) # 1D
np.random.rand(3,4) # 2D

# 2. randint [)- random integers between a specified range.
np.random.randint(1,10) # Generate a random integer in [1,10)
np.random.randint(1,10,size=(3,3))  # 2D

# 3. randn -  Generates random numbers from a standard normal distribution
arr = np.random.randn(500000)
arr_2d = np.random.randn(2, 3)

### Reshape fun 

In [35]:
# does not change orignal array
# sizes should match before and after
a=np.random.randint(1,11,size=(3,4))
print(a)
#print(a.shape) # (3,4)

ar=a.reshape(4,3)
ar

[[ 6  7  8  9]
 [ 4 10  7  2]
 [ 8  8  4  5]]


array([[ 6,  7,  8],
       [ 9,  4, 10],
       [ 7,  2,  8],
       [ 8,  4,  5]])

### Linspace fun

In [72]:
# numpy.linspace(start, stop, num=50) 

np.linspace(1,10,10) # 10 evenly spaced values fomr 1 to 10
# by default, numpy.linspace() generates 50 evenly spaced elements between the specified start and stop values.

np.linspace(0,20,5)



a=np.random.randint(1,10,size=(3,4))
print(a)
f=a.flatten() # makes 1D
print(f)

[[3 1 3 1]
 [6 4 4 7]
 [8 6 4 4]]
[3 1 3 1 6 4 4 7 8 6 4 4]


### Logspace fun

In [3]:
# numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)

# to generate 10 numbers evenly spaced between 10 and 1000 on log scale 

np.logspace(1,3,num=10,base=10)


array([  10.        ,   16.68100537,   27.82559402,   46.41588834,
         77.42636827,  129.1549665 ,  215.443469  ,  359.38136638,
        599.48425032, 1000.        ])

### copy fun

In [9]:
a1=np.array([1,2,3,4])
a2=a1
print(a1,a2)
print(id(a1),id(a2)) # same 


# copy function
a2=np.copy(a1)
print(a2)
print(id(a1),id(a2)) # different 

[1 2 3 4] [1 2 3 4]
1763013797616 1763013797616
[1 2 3 4]
1763013797616 1763014860496


### Min, Max, Sum

In [18]:
a=np.array([1,2,3,4,5])
a

a.max() # max value
a.min() # min value
a.sum() # sum of all 

15

In [25]:
# For multidimensional arrays
a=np.random.randint(1,10,(3,4))
print(a)

print(a.max(),a.min(), a.sum())

# for columns
print(a.max(axis=0)) # max value in each col
print(a.min(axis=0))
print(a.sum(axis=0))

# for rows
print(a.max(axis=1)) # max value in each row
print(a.min(axis=1))
print(a.sum(axis=1))

[[5 4 2 4]
 [3 2 3 1]
 [5 2 9 4]]
9 1 44
[5 4 9 4]
[3 2 2 1]
[13  8 14  9]
[5 3 9]
[2 1 2]
[15  9 20]


### Seed fun

In [30]:
np.random.seed(3)
a=np.random.randint(1,10,(3,5))
a

array([[9, 4, 9, 9, 1],
       [6, 4, 6, 8, 7],
       [1, 5, 8, 9, 2]])

### Sorting

In [41]:
print(a,"\n")
np.sort(a) # sorts rowwise (not change original array)

print(np.sort(a,axis=0),'\n') # sorts colwise
print(np.sort(a,axis=1)) # sorts rowwise

# to sort entire array, flatten it, sort it , reshape to original shape
np.reshape(np.sort(a.flatten()),(3,5))


# we can also give the type of sort
print(np.sort(a,kind='mergesort'))

[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]] 

[[1 4 6 8 1]
 [6 4 8 9 2]
 [9 5 9 9 7]] 

[[1 4 9 9 9]
 [4 6 6 7 8]
 [1 2 5 8 9]]
[[1 4 9 9 9]
 [4 6 6 7 8]
 [1 2 5 8 9]]


### Mathematical Ops

In [59]:
np.random.seed(3)
a=np.random.randint(1,10,(3,5))
print(a)

a+1 # add 1 to all elements
a-1
a/2
a*2
a//2
a%2
a**2 # power


# matrix multiplication
# The number of columns in a1 must equal the number of rows in a2
a1=np.array([[1,2],[3,4]])
a2=np.array([[3,4],[2,1]])
a1.dot(a2)

# operates on respective elements 
a1+a2
a1-a2
a1*a2
a1/a2


[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
[[11  6 11 11  3]
 [ 4  6  4 10  5]
 [ 3  7 10 11  0]]
[[81 16 81 81  1]
 [36 16 36 64 49]
 [ 1 25 64 81  4]]


### Percentile fun

In [63]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10])

# Calculate the 50th percentile (median)
p50 = np.percentile(data, 50)
print("50th Percentile:", p50)

p90 = np.percentile(data, 90)
print("90th Percentile:", p90)

50th Percentile: 5.5
90th Percentile: 9.1


### Mean, Variance, SD

In [72]:
a=np.array([1,2,3,4,5])
print(a)

print(a.mean())
print(a.var())
print(a.std())

a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2.mean() # for flattened array
a2.mean(axis=1) # rowwsie mean
a2.var(axis=0) # colwise variance

[1 2 3 4 5]
3.0
2.0
1.4142135623730951


array([6., 6., 6.])

### Filtering numpy array

In [83]:
a=np.arange(1,10)
print(a)

print(a>5)
a[a>5]

# replace all values above 5 with 10
a[a>5]=10
a


[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]


array([ 1,  2,  3,  4,  5, 10, 10, 10, 10])

### Transpose

In [86]:
a=np.random.randint(1,10,(3,5))
print(a)
print(a.T) # transpose of a

[[2 2 6 6 8]
 [5 4 1 1 1]
 [1 3 3 8 1]]
[[2 5 1]
 [2 4 3]
 [6 1 3]
 [6 1 8]
 [8 1 1]]


### Where function

In [91]:
a=np.random.randint(1,100,10)
print(a)

# return even or odd 
np.where(a%2==0,'even','odd')

[40 51 66 36 46 53  2 19 64  3]


array(['even', 'odd', 'even', 'even', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

### Merge arrays

In [107]:
# using concatenation
a1=np.array([[1,1,1],[2,2,2],[3,3,3]])
a2=np.array([[1,2,3],[4,5,6],[1,1,1]])

print(a1,'\n\n',a2)

np.concatenate((a1,a2))  # rowwise
np.concatenate((a1,a2),axis=0) # rowwise
np.concatenate((a1,a2),axis=1) # colwise



# using vstack and hstack
np.hstack((a1,a2)) # similar to axis=1 , along cols
np.vstack((a1,a2)) # similar to axis=0 , along rows


[[1 1 1]
 [2 2 2]
 [3 3 3]] 

 [[1 2 3]
 [4 5 6]
 [1 1 1]]


array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

### Split arrays

In [116]:
a=np.random.randint(1,10,(4,4))
print(a)
#splits must divide the array into equal parts along the specified axis

np.vsplit(a,2) # vertival split
np.hsplit(a,2) # horizontal split


[[1 4 8 4]
 [6 7 2 6]
 [4 7 9 6]
 [7 8 1 3]]


[array([[1, 4],
        [6, 7],
        [4, 7],
        [7, 8]]),
 array([[8, 4],
        [2, 6],
        [9, 6],
        [1, 3]])]